{
 "title": "SysEleven - Quotas",
 "description": "Dashboard for SysEleven Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SysEleven - Compute Cores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SysEleven - Compute Cores",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_compute_cores_used / syseleven_compute_cores_total) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Compute Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPUs" } },
   "yaxes": [
    { "format": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_cores_used) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Compute Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPUs" } },
   "yaxes": [
    { "format": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_cores_total) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  { "title": "SysEleven - Compute Ram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "SysEleven - Compute Ram",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_compute_ram_used_megabytes / syseleven_compute_ram_total_megabytes) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Compute Ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_ram_used_megabytes ) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Compute Ram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_ram_total_megabytes) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  { "title": "SysEleven - S3 Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SysEleven - S3Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_s3_space_used_bytes / syseleven_s3_space_total_bytes) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - S3 Used Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_s3_space_used_bytes) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - S3 Total Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_s3_space_total_bytes) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  { "title": "SysEleven - Volume Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "SysEleven - Volume Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_volume_space_used_gigabytes / syseleven_volume_space_total_gigabytes) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Volume Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_space_used_gigabytes ) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Volume Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_space_total_gigabytes) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  { "title": "SysEleven - Volume Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "SysEleven - Volume Volumes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_volume_volumes_used / syseleven_volume_volumes_total) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Volumes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_volumes_used) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Volumes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_volume_volumes_total) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  { "title": "SysEleven - Compute Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "SysEleven - Compute Instances",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_compute_instances_used / syseleven_compute_instances_total) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Compute Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "yaxes": [
    { "format": "Instances" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_instances_used ) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Compute Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "yaxes": [
    { "format": "Instances" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_compute_instances_total) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Network LoadBalancers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "SysEleven - Network LoadBalancers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_network_loadbalancers_used / syseleven_network_loadbalancers_total) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Network LoadBalancers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_network_loadbalancers_used ) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Network LoadBalancers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_network_loadbalancers_total) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Network Floating IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "SysEleven - Network Floating IPs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_network_floating_ips_used / syseleven_network_floating_ips_total) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used Network Floating IPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "IPs" } },
   "yaxes": [
    { "format": "IPs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_network_floating_ips_used ) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total Network Floating IPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "IPs" } },
   "yaxes": [
    { "format": "IPs" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_network_floating_ips_total) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  { "title": "SysEleven - DNS Zones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "SysEleven - DNS Zones",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((syseleven_dns_zones_used / syseleven_dns_zones_total) * 100) by(region, project)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "SysEleven - Used DNS Zones",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Zones" } },
   "yaxes": [
    { "format": "Zones" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_dns_zones_used ) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  },
  {
   "title": "SysEleven - Total DNS Zones",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Zones" } },
   "yaxes": [
    { "format": "Zones" }
   ],
   "targets": [
    {
     "expr": "sum(syseleven_dns_zones_total) by(region, project) ",
     "legendFormat": "{{region}} "
    }
   ]
  }
 ]
}